### ISSUE TITLE
来了

### ISSUE THREAD

**Issue by y377** [kingwrcy/hotnews#1]
> 现在都在做垂直领域

**如果项目不甘心，应当换个方向或思路**；我们正在做母婴生态链，可以私聊我，搏一搏，单车变摩托

**Comment by kingwrcy** [comment]
老板你发跟这个项目没关系吧

**Comment by y377** [comment]
> 老板你发跟这个项目没关系吧

怪我，没说清楚，你说论坛发展难，我意思论坛想要发展，要切换到其他的细分领域，比如论坛不要再搞什么IT技术分享了，搞母婴，搞农业，搞养殖等等，你现在再想一想跟项目有没有关系？

**Comment by kingwrcy** [comment]
老哥我明白你意思，可是我这没有你说的那些圈子，你有资源？

我一个外人不好进入，你有资源有能力的话看需要这个项目配合你什么。

**Comment by y377** [comment]
> 老哥我明白你意思，可是我这没有你说的那些圈子，你有资源？
> 
> 我一个外人不好进入，你有资源有能力的话看需要这个项目配合你什么。

加V `iswiki`，我跟你好好聊聊愿景和规划
